### ISSUE TITLE
[Common] Buttons broken

### ISSUE THREAD

**Issue by JosiahKunz** [JosiahKunz/Beamline-Architect#14]
Can't press Ok:

![image](https://user-images.githubusercontent.com/26817935/31311605-dbdd5b74-ab7d-11e7-8276-6eb7d705c7ec.png)

Likely due to changing the Text object into a TextPro object.

**Comment by JosiahKunz** [comment]
Specifically, on G4BL Absorber.

**Comment by JosiahKunz** [comment]
Appears to be code-related @cmconrad. Full error message:

> NullReferenceException: Object reference not set to an instance of an object
Popup.GetTextFromInputField (System.String name) (at Assets/Resources/Scripts/Common/UI Rendering/Popup.cs:466)
ABS_G4BL.ApplyOptions (UnityEngine.GameObject go) (at Assets/Resources/Scripts/G4BL/Elements/ABS.cs:230)
ElementList_G4BL.ApplyOptionsToElement (Int32 i) (at Assets/Resources/Scripts/G4BL/Logic/ElementList.cs:213)
Popup.ApplyOptionsToElement (Int32 i) (at Assets/Resources/Scripts/Common/UI Rendering/Popup.cs:359)
Popup.OnClose () (at Assets/Resources/Scripts/Common/UI
Rendering/Popup.cs:301)
StaticHandler.UpdatePopup () (at Assets/Resources/Scripts/Common/Logic/StaticHandler.cs:92)
StaticHandler.Update () (at Assets/Resources/Scripts/Common/Logic/StaticHandler.cs:9)

**Comment by cmconrad** [comment]
*Absorber Window key value pair looked for the incorrect string. Fixed now.
