### ISSUE TITLE
[G4BL] Materials need reconfiguring

### ISSUE THREAD

**Issue by JosiahKunz** [JosiahKunz/Beamline-Architect#15]
Instead of materials as InputFields, they should be Searchable Dropdowns. I.e., instead of:

![image](https://user-images.githubusercontent.com/26817935/31311633-4e91df64-ab7e-11e7-9a96-f494e0bd1209.png)

they should be:

![image](https://user-images.githubusercontent.com/26817935/31311637-61562ae2-ab7e-11e7-809f-d67795d96593.png)

See the G4BL MQ for an example of how to set this up.

**Comment by cmconrad** [comment]
Fixed over break.
