### ISSUE TITLE
[COSY] CMST options

### ISSUE THREAD

**Issue by JosiahKunz** [JosiahKunz/Beamline-Architect#22]
When dragging a CMST element, it should say "Current • turns per meter (A)" (current times turns per meter in Amps). Also, "Inner radius aperture (m)" should just be "Inner radius (m)".

![image](https://user-images.githubusercontent.com/26817935/31311692-c8090ac4-ab7f-11e7-8eb5-9283c58bd5dc.png)

**Comment by lmr5587** [comment]
Is the text "Current • turns per meter (A)" for the element long name or the option title?

**Comment by JosiahKunz** [comment]
Just the option title (second blue box on the left). I was doing these fairly quickly---now I see that sentence is a little unclear :)

**Comment by JosiahKunz** [comment]
Also, I think we need to watch our capitalization. If we're going to say `Z Location (m)` (both `Z` and `L` capitalized), we need to say `Current • Turns per Meter (A)`. I haven't been paying much attention to capitalization, so I'm probably to blame here.

**Comment by lmr5587** [comment]
Made adjustments and checked for capitalization inconsistencies.
