### ISSUE TITLE
[Python] Need base implementation of plotting

### ISSUE THREAD

**Issue by JosiahKunz** [JosiahKunz/Beamline-Architect#27]
We've already talked about this, but I thought I'd add it to the task list for completion's sake =)

**Comment by hebower** [comment]
Functionality Implemented
#Any number of plots
#Any number of variables per plot
#Plot title, axis labels
#Any number of variables per subplot
#Any color for each data item (must be in a specific order)
#Any location for the legend
#Subplots in any location
#Any number of subplots
