### ISSUE TITLE
Texture " is degenerate

### ISSUE THREAD

**Issue by cmconrad** [JosiahKunz/Beamline-Architect#36]
Upon making a two absorbers the background would throw an error in the console:

Texture '' is degenerate (dimensions 0x0)
UnityEngine.Texture2D:SetPixel(Int32, Int32, Color)
BackgroundGenerator:SetBorderPixel(Int32, Int32) (at Assets/Resources/Scripts/Common/UI Rendering/BackgroundGenerator.cs:250)
BackgroundGenerator:Refresh() (at Assets/Resources/Scripts/Common/UI Rendering/BackgroundGenerator.cs:228)
BackgroundGenerator:Start() (at Assets/Resources/Scripts/Common/UI Rendering/BackgroundGenerator.cs:87)

**Comment by JosiahKunz** [comment]
Prefabs were indeed instantiated with no width or height. They needed a frame for their sizes to be determined by the GridLayoutGroup. Therefore, under `Refresh ()`, I've inserted:
```
if (width == 0 || height == 0)
			return;
```
