### ISSUE TITLE
[Common] Popup Units

### ISSUE THREAD

**Issue by JosiahKunz** [JosiahKunz/Beamline-Architect#47]
Popup units should be underneath. To implement, use newline character in Popup commands (i.e., \n). Below: top and bottom look good, but middle does not!

![image](https://user-images.githubusercontent.com/26817935/33579525-25a87c4e-d918-11e7-98e6-1acc4ab7ac2c.png)

**Comment by cmconrad** [comment]
![image](https://user-images.githubusercontent.com/25870114/34222197-be9a4186-e588-11e7-9263-0f1b9f1147f4.png)

Spacing looks too tight and strange with short keys. We could move the units to the right hand side of the values.

**Comment by JosiahKunz** [comment]
Pinging @cmconrad and @lmr5587 for opinions.

This is better, but I'm not sure how much better. Maybe we should just leave it single-lined (e.g., `Height (mm)`).

![image](https://user-images.githubusercontent.com/26817935/34365624-3f642a3a-ea60-11e7-9239-34c77dbb01b8.png)

**Comment by JosiahKunz** [comment]
Here's the single-lined version:

![image](https://user-images.githubusercontent.com/26817935/34365642-73b2dffc-ea60-11e7-953f-558d8accfdd0.png)

I think this one has my vote.
